### ISSUE TITLE
Fail to install repo csr_processor.xqm

### ISSUE THREAD

**Issue by yatesr** [openhie/openinfoman#20]
When installing the repo csr_processor I get this error.
````
root@test:/opt/openinfoman/repo# basex -Vc "repo install csr_processor.xqm"
Stopped at /opt/openinfoman/repo/csr_processor.xqm, 120/77:
[XPST0017] Unknown function 'map:new'.
`````
All of the other repos install fine except this one.  I am using the latest basex snapshot from 2014-12-25. http://files.basex.org/releases/BaseX-latest.zip

**Comment by litlfred** [comment]
Hi,
This was due to a change in basex where map:new() is replaced with map:merge().  The commit https://github.com/openhie/openinfoman/commit/115e606dbdc0970da4248020c6d4e2d387f8574e fixes this.

**Comment by litlfred** [comment]
(I haven't checked if any other the other associated repos have the same issue or not... please let me know if you have any issues)
