### ISSUE TITLE
Stored queries not showing up

### ISSUE THREAD

**Issue by yatesr** [openhie/openinfoman#21]
I think this may be a configuration issue, but I cant seem to figure out the issue.  After the install I go to http://server:8984/CSD -> CSD Endpoints -> Load and Register Sample Service Directories, I get this error.
````
HTTP ERROR 400

Problem accessing /CSD/initSampleDirectory. Reason:

    Stopped at /opt/basex/repo/com/github/openhie/openinfoman/csd_lsd.xqm, 24/27:
[file:not-found] File '/../resources/service_directories' does not exist.

Stack Trace:
- /opt/basex/webapp/initSampleDirectories.xqm, 79/12
Powered by Jetty://
````
Also when going to manage stored functions I have 0 even after reloading from disk.  I have the follow symlinks setting in basex set, and have them symlinked to the `stored_query_definitions` directory in basex/resources

Any idea where to start troubleshooting?

**Comment by litlfred** [comment]
by default it is/was looking for locations relative to the directory that basex was started in. where did you start it from?  it kinda looks like you started it in /
Cheers,
-carl

**Comment by yatesr** [comment]
I was wondering where it was getting that initial directory. I am using an init script, so I just changed it to cd to the basex/bin dir before executing, and that fixed the problem. Thanks!
