### ISSUE TITLE
Error when configuring openinfoman package during install

### ISSUE THREAD

**Issue by yatesr** [openhie/openinfoman#23]
When installing the openinfoman package, version 1.0.38~trusty, I get the error below in the log section.  It looks like it is trying [this](https://github.com/openhie/openinfoman/blob/master/packaging/targets/trusty/debian/postinst#L52) before the service is up.  I think maybe allowing it to try a few times with a few seconds delay each time would fix this. If I have time I'll send a PR for this. 

Log
````
+ service openinfoman start
openinfoman start/running, process 5124
+ /usr/bin/wget http://localhost:8984/CSD/storedFunctions/reload -O /dev/null
--2015-10-28 11:22:27--  http://localhost:8984/CSD/storedFunctions/reload
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8984... failed: Connection refused.
dpkg: error processing package openinfoman (--configure):
 subprocess installed post-installation script returned error exit status 4
Setting up lksctp-tools (1.0.15+dfsg-1) ...
Errors were encountered while processing:
 openinfoman
E: Sub-process /usr/bin/dpkg returned an error code (1)
````

**Comment by litlfred** [comment]
Thanks for reporting this Ryan.  This is strange, looking here:
  https://github.com/openhie/openinfoman/blob/master/packaging/targets/vivid/debian/postinst <https://github.com/openhie/openinfoman/blob/master/packaging/targets/vivid/debian/postinst>
the service is started on line 51 and then on line 53 the wget call is made.  I am guessing “service start” kicks off a child process to actually start openinfoman, so it doesn’t necessarily wait until that child process returns.  Maybe we just need a sleep on line 52?
Cheers,
-carl

**Comment by yatesr** [comment]
I went ahead and added a 10s sleep in my PR.  A more elegant solution might be to keep retrying until we receive a HTTP 200 back with a timeout of 10 seconds or so, but this should work for now.

**Comment by litlfred** [comment]
OK.  Cool.

Let me know if you want to go over the package building process at some point…

Cheers,
-carl

**Comment by yatesr** [comment]
I am seeing a new error now when installing openinfoman from a fresh install.  I did not encounter this on upgrading a previous installation. 

I receive the same error when running the same command `wget http://localhost:8984/CSD/storedFunctions/reload` on the host.  I am able to load the stored functions by navigating to `http://localhost:8984/CSD/storedFunctions` and clicking reload from disk from a web browser. 
````
+ service openinfoman start
openinfoman start/running, process 16030
+ sleep 10
+ /usr/bin/wget http://localhost:8984/CSD/storedFunctions/reload -O /dev/null
--2015-10-29 11:30:01--  http://localhost:8984/CSD/storedFunctions/reload
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8984... connected.
HTTP request sent, awaiting response... 400 Stopped at /var/lib/openinfoman/repo/com/github/openhie/openinfoman/csr_proc.xqm, 97/3: [XUDY0027] Insert target must not be empty.  Stack Trace: - /var/lib/openinfoman/webapp/storedFunctions.xqm, 156/37
2015-10-29 11:30:10 ERROR 400: Stopped at /var/lib/openinfoman/repo/com/github/openhie/openinfoman/csr_proc.xqm, 97/3: [XUDY0027] Insert target must not be empty.  Stack Trace: - /var/lib/openinfoman/webapp/storedFunctions.xqm, 156/37.

dpkg: error processing package openinfoman (--configure):
 subprocess installed post-installation script returned error exit status 8
Setting up lksctp-tools (1.0.15+dfsg-1) ...
E: Sub-process /usr/bin/dpkg returned an error code (1)
````

**Comment by litlfred** [comment]
OK.  This is because the document storing the metadata on stored queries hasn’t been initialized yet, I think.

You will need to hit 
	http://localhost:8984/CSD/storedFunctions/init
first.

You will get the same thing when initializing SVS.  For this, you will need to hit:
  http://localhost:8984/CSD/SVS/initSharedValueSet/init
first.

Cheers,
-carl

**Comment by yatesr** [comment]
Yep, that worked I added the SVS set in #25 as well as the fix for this.
