### ISSUE TITLE
terminate line 19 : csd_webapp_config.xqm 

### ISSUE THREAD

**Issue by dannkhoma** [openhie/openinfoman#26]
Line 19 not terminated, got an error on linking openinforman libraries to basex repository

**Comment by litlfred** [comment]
Which version do you have installed?  There was an issue I thought was
fixed.

Cheers,
-carl

**Comment by dannkhoma** [comment]
Pulled latest version, file csd_webapp_config.xqm, updated four days ago. Im using the basex snapshot version 8.3

**Comment by litlfred** [comment]
I (think I) have fixed it with the following commit:
  https://github.com/openhie/openinfoman/commit/58b81ca64adee592121f97745c535113b3deed8d
If you can confirm that it fixes the issue, then please feel free to close the issue.

I would also recommend you try the new Ubuntu packaging.  It generates the needed config during install.

**Comment by dannkhoma** [comment]
Yes this has fixed the issue, let me also try the Ubuntu packaging. Thanks

Cheers
