### ISSUE TITLE
anonymous.xml has invalid dateTime

### ISSUE THREAD

**Issue by craigappl** [openhie/openinfoman#29]
The anonymous.xml sample document includes a dateTime that has both a decimal ss.sss and a time zone of +0000 on all dates. This is causing an error in the XML validator.

http://www.freeformatter.com/xml-validator-xsd.html

XML Input: https://raw.githubusercontent.com/openhie/openinfoman/master/resources/service_directories/anonymous.xml
XSD Input: https://github.com/openhie/openinfoman/raw/master/resources/CSD.xsd

Error: Cvc-datatype-valid.1.2.1: '2013-06-25T16:45:13.000+0000' Is Not A Valid Value For 'dateTime'.. Line '7', Column '155'.

The [xs:dateTime](http://docstore.mik.ua/orelly/xml/schema/ch16_01.htm#ch16-77031) seems to allow for either seconds with decimal points (ss.sss) or seconds with timezones (ss+0000).

Removing the +0000 passes the XML validation checks and retains the time.

**Comment by craigappl** [comment]
Update:
I removed the +0000 and the validation checks are complete for the dateTime, but I'm getting a bunch of namespace validation errors for contact points.

http://www.freeformatter.com/xml-validator-xsd.html

XML Input: https://raw.githubusercontent.com/craigappl/openinfoman/master/resources/service_directories/anonymous.xml
XSD Input: https://github.com/openhie/openinfoman/raw/master/resources/CSD.xsd

Here's a sample of the top 3 lines of errors:
Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'csd:contact'. One Of '{"urn:ihe:iti:csd:2013":extension, "urn:ihe:iti:csd:2013":record}' Is Expected.. Line '115', Column '20'.
Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'csd:codedType'. One Of '{"urn:ihe:iti:csd:2013":provider, "urn:ihe:iti:csd:2013":person}' Is Expected.. Line '116', Column '106'.
Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'csd:codedType'. One Of '{"urn:ihe:iti:csd:2013":provider, "urn:ihe:iti:csd:2013":person}' Is Expected.. Line '227', Column '106'.

FYI @litlfred

**Comment by litlfred** [comment]
Hi, This has been fixed with:
 https://github.com/openhie/openinfoman/commit/9e5ac1bdab6b6d9bf9d1c2d1b1b41844f4934952

Sorry about that - it was an old export.   

FYI.. there is a new commit against CSD.xsd for an upcoming change proposal to CSD.
