### ISSUE TITLE
shared value sets don't load - path issue

### ISSUE THREAD

**Issue by citizenrich** [openhie/openinfoman#31]
Trying to reach http://localhost:8984/CSD/SVS/initSharedValueSet fails.

The error is:
Stopped at /home/richard/openinfoman/repo/com/github/openhie/openinfoman/svs_lsvs.xqm, 120/25:
[file:no-dir] ‘/home/richard/../resources/shared_value_sets’ is no directory.

The problematic line in svs_lsvs.xqm is:
declare variable $svs_lsvs:base_path := concat(file:current-dir() ,'../resources/shared_value_sets/');

If this is changed to an absolute path it works:
declare variable $svs_lsvs:base_path := '/Users/richard/openinfoman/resources/shared_value_sets/';

**Comment by litlfred** [comment]
Does file:current-dir() end in a slash?

**Comment by citizenrich** [comment]
https://github.com/openhie/openinfoman/pull/32
